# replace weights_directory with either:
# * the *ABSOLUTE PATH* to where you store your weights, or
# * the huggingface repo with your weights

[llama-3.1-8b]
weights_directory = meta-llama/Llama-3.1-8B
name = LLaMA-3.1-8B
probe_layer = 12
intervene_layer = 8
noperiod = False